### ISSUE TITLE
Reproducibilty problem

### ISSUE THREAD

**Issue by akshitac8** [nasir6/zero_shot_detection#3]
Hello @nasir,

I am not able to reproduce the numbers mentioned in the paper. I am getiing a classification accuracy of 46.7. It would be really helpful if you could have a look at the issue.

**Comment by akshitac8** [comment]
Thank you @nasir6 for the help I was able to get the results

**Comment by sandipan211** [comment]
@akshitac8 @nasir6  Could you please share how did you solve the reproducibility problem? I've been trying for a long time but still not getting the results mentioned in the paper...it's less than that. Could you please help?

**Comment by GuangyuanLiu1999** [comment]
> Thank you @nasir6 for the help I was able to get the results

Hello sir, I want to ask you how to reproduce the results of the paper.
