### ISSUE TITLE
How to get VOC results?

### ISSUE THREAD

**Issue by zwy1996** [nasir6/zero_shot_detection#6]
Hi,

Nice work!
I was very sorry to bother you.
When I used your code, I found I could not get VOC result, where the instructions of voc?

Thanks very much!

**Comment by nasir6** [comment]
@zwy1996 can you elaborate what issue did you face?

**Comment by zwy1996** [comment]
Thanks for your response. I have solved the question. It was my mistake.

Thank you again!

**Comment by AmingWu** [comment]
@zwy1996 , How long do you train?

**Comment by AmingWu** [comment]
![QQ截图20210128103133](https://user-images.githubusercontent.com/38445175/106081612-21f84d00-6154-11eb-8b08-cf913c571b44.png)
When I create the environment, I meet this problem. Could you give me some advice? Thank you
